/**
 * Complete Cryptographic Verification Test Suite for @privacyscrubber/mcp-server
 */

import { createRequire } from 'module';
import path from 'path';
import { fileURLToPath } from 'url';

const require = createRequire(import.meta.url);
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const scrubberCorePath = path.resolve(__dirname, './scrubber-core.cjs');
const mcpServerIndex = path.resolve(__dirname, 'index.js');

console.log("Loading modules for verification test...");
try {
  const PrivacyScrubberCore = require(scrubberCorePath);
  PrivacyScrubberCore.init();

  // Load index.js to test its internal validate functions
  // We can simulate its checkLicenseStatus by mocking environment variables
  const indexModule = await import('./index.js?update=' + Date.now());

  // Test Case 1: No license key
  console.log("\n[Test 1] Testing with no license key (Free tier)...");
  process.env.PRIVACYSCRUBBER_KEY = "";
  const t1 = global.checkLicenseStatus ? global.checkLicenseStatus() : mockCheckLicenseStatus();
  console.log("Status:", t1);
  if (t1.isPro) {
    console.error("❌ Test 1 failed: keyless state should not be PRO.");
    process.exit(1);
  }
  console.log("✅ Test 1 passed.");

  // Test Case 2: Expired trial key
  console.log("\n[Test 2] Testing with expired signed trial key...");
  // Expired key generated by generate-license.js
  const expiredKey = "eyJ0eXBlIjoidHJpYWwiLCJleHBpcmVzIjoxNzgzMjcwMTgzLCJpc3N1ZWRBdCI6MTc4MzcwMjE4Mywibm9uY2UiOiIzYzRkYzEwNmRkOGJiZjczIn0=.Wc1cPwvRpEQxG3BarmedBYm9sUsGdwznboh8Gx3a7qQZm2I+Dha8lk1CtzmaaBt5O8pQszGuTCHapASFwZX2Ku8uZxkGipPI+tbNI39KK7cM6wA+Txc0Ufec/lnDE/27WelBswStSIMgR5LPVScfamMO5BK6jvJ9RgOrEdJeqJPcpab0mwy4jzZwSATyZ1JOS61i8ZlJ+n99zppBrrMZQQo/FJ5t70RpqZiZoMuyNbeDJB9UWGDEAELiJLBkaGeYgBo65zp7fRcTuyjmoZjINnOhCcXmKsmeB1vkHdjPg8jXaGVWFN7bJryeV7j/OkpNqO2q74x3hXDvNwlGtg4PUg==";
  process.env.PRIVACYSCRUBBER_KEY = expiredKey;
  const t2 = mockCheckLicenseStatus();
  console.log("Status:", t2);
  if (t2.isPro || !t2.error.includes("expired")) {
    console.error("❌ Test 2 failed: expired key should be blocked with expiration reason.");
    process.exit(1);
  }
  console.log("✅ Test 2 passed.");

  // Test Case 3: Valid signed PRO key
  console.log("\n[Test 3] Testing with valid signed PRO key...");
  // Valid key generated in this session
  const validKey = "eyJ0eXBlIjoicHJvIiwiZXhwaXJlcyI6MjA5OTA2MjE3NCwiaXNzdWVkQXQiOjE3ODM3MDIxNzQsIm5vbmNlIjoiMmI4MTllN2ZmM2ZmOTFmYiJ9.ZmhaKDGf9vG0nTH0nyOy3EInsuUmzjBOk9IOyiqzt6Y5s3UG+2yRExuKBoeXWymbpJt3NIJNM9sVxxl+lcop5wqbi2LNtPY4MuwBRA7pO4nn3Bes5R0lxLbEYVE8Iiw3zbfK4uVYQ53BJ7El6JCeFKPJ5WbKUsPLsjb1Lr2iQzW3ODOMaM5jKdgAGcNpuWQ373D7SW7I03Jec9kvP5hL7j3u4DV8ZzuQFzy2Nh+uMH54suydg2sNIpxrRQyxpGv7rZjTO1KT+xzzqnjqX4Pein0e6GrC5E4JUEggADtXPFMKW5SEiWzeeirB5RUPMO/F927S5fFuOYHAfuar2FqErA==";
  process.env.PRIVACYSCRUBBER_KEY = validKey;
  const t3 = mockCheckLicenseStatus();
  console.log("Status:", t3);
  if (!t3.isPro) {
    console.error("❌ Test 3 failed: valid key was not accepted.");
    process.exit(1);
  }
  console.log("✅ Test 3 passed.");

  console.log("\n🎉 All local cryptographic validation tests passed!");
  process.exit(0);

} catch (error) {
  console.error("❌ Test run crashed:", error);
  process.exit(1);
}

// Mock checker mapping index.js logic locally for direct assertion
function mockCheckLicenseStatus() {
  const crypto = require('crypto');
  const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw3f37srO402PU4++Baf8
FG8LY4l/IA3NKLlBnYmNHRTjfI/O/w5PDZn1xPcUQevojA1J+A5moKcjXsJ5b21X
hJoYSkE4vLpcVYOt1FhRwEHs1APDSyss0HixboLz2eW2XQf2NbwajWtNlyxvgczO
KE6ClnLomtsaKywwqB4alzdYnnnFJttFPjwmgPSO7D9AgN9sYaVkXOaOFrIZ90Ng
TRhSHUeL7ReltWlCHwz9xf5m2FrKtxr2VBlEoyPjsFzalHMey1EX+yXe81zM7IIi
t1Z8agLzo7WIfNBAIWmRlerTplaFFZrQgdF5g/Y0n8IIMZOtadgoY8E855psDNZV
7wIDAQAB
-----END PUBLIC KEY-----`;

  const key = (process.env.PRIVACYSCRUBBER_KEY || "").trim();
  if (!key) return { isPro: false, type: null, error: "No license key provided." };

  try {
    const [payloadBase64, signatureBase64] = key.split('.');
    if (!payloadBase64 || !signatureBase64) {
      return { isPro: false, type: null, error: "Invalid license key structure." };
    }

    const verifier = crypto.createVerify('SHA256');
    verifier.update(payloadBase64);
    const isVerified = verifier.verify(PUBLIC_KEY, signatureBase64, 'base64');
    
    if (!isVerified) {
      return { isPro: false, type: null, error: "Signature verification failed." };
    }

    const payload = JSON.parse(Buffer.from(payloadBase64, 'base64').toString('utf8'));
    
    if (payload.expires && payload.expires < Math.floor(Date.now() / 1000)) {
      return { 
        isPro: false, 
        type: payload.type, 
        error: `License expired on ${new Date(payload.expires * 1000).toLocaleDateString()}` 
      };
    }

    return { isPro: true, type: payload.type, error: null };
  } catch (e) {
    return { isPro: false, type: null, error: "Error parsing license: " + e.message };
  }
}
